pipeline:
  identifier: gxls
  name: gxls
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitforronak
        repoName: xls
        build: <+input>
  stages:
    - stage:
        identifier: build
        type: CI
        name: build
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  identifier: restore_bazel_cache
                  type: RestoreCacheGCS
                  name: restore bazel cache
                  spec:
                    connectorRef: ronakgcpbucket
                    bucket: migration-artifact-comman
                    key: bazel
                    archiveFormat: Tar
                  when:
                    stageStatus: Success
                    condition: "false"
                  failureStrategies: []
              - step:
                  identifier: d
                  type: Run
                  name: install bazel
                  spec:
                    shell: Bash
                    command: |-
                      # python --version
                      # sudo ls /usr/bin/python*
                      # sudo add-apt-repository ppa:deadsnakes/ppa
                      # sudo apt install python3.8 -y
                      # sudo ls /usr/bin/python*
                      # sudo ln -sf /usr/bin/python3.8 /usr/bin/python3 
                      # python --version





                       sudo curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
                       sudo mkdir -p "bin/"
                       sudo mv bazelisk-linux-amd64 "bin/bazel"
                       sudo chmod +x "bin/bazel"

                       sudo apt-get install python3-dev python3-distutils python3-dev python-is-python3 libtinfo5
              - step:
                  identifier: Bazel_Build_Fuzz_Driver
                  type: Run
                  name: Bazel Build Fuzz Driver
                  spec:
                    shell: Bash
                    command: |-
                      ls -a 
                      tree -a -L 2
                      sudo -H "bin/bazel" build -c opt xls/fuzzer:run_fuzz_multiprocess

                      ls -a 
                      tree -a -L 2

                      # cd /home/ubuntu/.cache
                      # ls -a 
                      # tree -a -L 2
              - step:
                  identifier: save_cache
                  type: SaveCacheGCS
                  name: save cache
                  spec:
                    connectorRef: ronakgcpbucket
                    bucket: migration-artifact-comman
                    key: bazel
                    sourcePaths:
                      - /home/ubuntu/.cache/bazel
                    archiveFormat: Tar
              - step:
                  identifier: Bazel_Run_Fuzz
                  type: Run
                  name: Bazel Run Fuzz
                  spec:
                    shell: Bash
                    command: sudo -H "bin/bazel" run -c opt xls/fuzzer:run_fuzz_multiprocess -- --crash_path "crashers" --sample_count=1024 --codegen=false --simulate=false --emit_loops=False --summary_path "crashers"
          sharedPaths:
            - /home/ubuntu/
